name: avataar_generator
description: A simple svg generator that gives awesome emojis.
version: 1.1.0
author: Kushagra Saxena <saxena.kushagra3107@gmail.com>
homepage: https://devslane.com
repository: https://github.com/devslane/Avataar-Generator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
